### ISSUE TITLE
 Open for First-Time Open Source Contributors: Enhance UI and Showcase Your Skills! 🎉

### ISSUE THREAD

**Issue by Mohd-FaiZ-Jr** [Mohd-FaiZ-Jr/Menu-Mate#6]
## First-Time Open Source Contributors: Enhance UI 🎨✨

Welcome, First-Time Open Source Contributors! 🎉 This issue is all about enhancing the UI of our project, and it's open to your creativity and ideas! Whether you're a beginner looking to dive into open source or a developer who loves experimenting with front-end design, this is the perfect opportunity to showcase your skills.

We encourage you to **improve the user interface** in any way you see fit—whether it's polishing the layout, refining the color scheme, adding interactive elements, or implementing new design features. Feel free to bring in any fresh ideas or try out UI/UX improvements that you've been wanting to experiment with. 

There are no strict requirements here—just bring your creativity, and let's make the interface more user-friendly and visually appealing!

Not only will you get hands-on experience with open source contributions, but you’ll also be able to put your unique touch on the project. Don’t hesitate to dive in and start improving the UI in your own style!

Happy coding, and have fun designing! 🎨✨

**Comment by namay26** [comment]
I have made a PR with some changes that felt right to me, please check and merge.
