### ISSUE TITLE
Rename the image file 2d-graphic-colourful-background.jpg .

### ISSUE THREAD

**Issue by Mohd-FaiZ-Jr** [Mohd-FaiZ-Jr/Menu-Mate#9]
In the directory code/img, you will find a 2d-graphic-colourful-background.jpg file. Rename it to colourful-background.jpg.

**Comment by prashantrai-30** [comment]
Hey @Mohd-FaiZ-Jr ,can you assign this to me.

**Comment by Mohd-FaiZ-Jr** [comment]
> Hey @Mohd-FaiZ-Jr ,can you assign this to me.

Yes sure.
